**First save a copy of this notebook in your Google drive.** Read this notebook from top to bottom and fill in the code as you go. Work together with your partner and discuss with other students in the class. Try to resolve any errors on your own first, but don't get stuck; ask for help!

For many of these questions, there are several ways to do it in Pandas. You only need to choose one that works. But you might want to experiment with multiple ways of doing the same thing to get practice working with Pandas.

## Titanic Data

 The Titanic data set (https://raw.githubusercontent.com/kevindavisross/data301/main/data/titanic.csv) contains information about 2206 passengers and crew members that were aboard the RMS Titanic when it sank on April 15, 1912.

1\. Read in the Titanic data set. What seems to be the observational unit?

**People**

In [45]:
# YOUR CODE HERE - ADD AS MANY CELLS AS YOU WANT
import pandas as pd
titanic = pd.read_csv("https://raw.githubusercontent.com/kevindavisross/data301/main/data/titanic.csv")

In [46]:
titanic.head()

,name,gender,age,class,embarked,country,ticketno,fare,survived,pclass,crew
0,"Abbing, Mr. Anthony",male,42.0,3rd,S,United States,5547.0,7.11,0,3.0,NaN
1,"Abbott, Mr. Eugene Joseph",male,13.0,3rd,S,United States,2673.0,20.05,0,3.0,NaN
2,"Abbott, Mr. Rossmore Edward",male,16.0,3rd,S,United States,2673.0,20.05,0,3.0,NaN
3,"Abbott, Mrs. Rhoda Mary 'Rosa'",female,39.0,3rd,S,England,2673.0,20.05,1,3.0,NaN
4,"Abelseth, Miss. Karen Marie",female,16.0,3rd,S,Norway,348125.0,7.13,1,3.0,NaN

2\. What column seems to be an appropriate index for this data frame? Can you think of any problems with using this column as the index?

**ticketno is likely the best index for this df. However, it seems that multiple people can be associated with the same ticketno if they bought it together**

3\. Regardless of your answer to the previous question, write code to make "name" the index of the data frame.

In [47]:
titanic_reindexed = titanic.set_index("name")

 4\. Write code that returns the observations for  "Kelly, Mr. James". What do you notice? (You can also try "Green, Mr. George"). Note: you might try this both with "name" as the index and with it not as the index.

In [48]:
titanic_reindexed.loc["Kelly, Mr. James"]

,gender,age,class,embarked,country,ticketno,fare,survived,pclass,crew
name,,,,,,,,,,
"Kelly, Mr. James",male,19.0,3rd,S,Scotland,363592.0,8.0100,0,3.0,NaN
"Kelly, Mr. James",male,44.0,3rd,Q,Ireland,330911.0,7.1607,0,3.0,NaN
"Kelly, Mr. James",male,44.0,engineering crew,S,England,NaN,NaN,0,NaN,engineering crew

5\. Write code to extract a single `DataFrame` containing the observations three members of the Widener family:
  - Widener, Mr. George Dunton
  - Widener, Mr. Harry Elkins
  - Widener, Mrs. Eleanor

What became of them? Using a search engine, what else can you learn about them? (Note: you could just provide a list of these names. But you might also want to experiment with functions for working with strings, e.g., [`str.contains`](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.contains.html) to find all instances of "Widener"; in this case, it might be helpful to have name as a regular column and not the index.)

**George and Harry died, Eleanor survived**

In [49]:
titanic_reindexed.loc[["Widener, Mr. George Dunton", "Widener, Mr. Harry Elkins", "Widener, Mrs. Eleanor"]]

,gender,age,class,embarked,country,ticketno,fare,survived,pclass,crew
name,,,,,,,,,,
"Widener, Mr. George Dunton",male,50.0,1st,S,United States,113503.0,211.1,0,1.0,NaN
"Widener, Mr. Harry Elkins",male,27.0,1st,S,United States,113503.0,211.1,0,1.0,NaN
"Widener, Mrs. Eleanor",female,50.0,1st,S,United States,113503.0,211.1,1,1.0,NaN

6\. Look at a few rows in the full data set. Try to identify what each variable measures. Also, try to identify each variable as either quantitative, categorical, or other. (In general, there should be a code book with information about all the variables. But try to infer what you can from context.)

**name: Categorical, gender: Categorical, age: Quantitative, class: Categorical, embarked: Categorical, country: Categorical, ticketno: Categorical, fare: Quantitative, survived: Categorical, pclass: Categorical**

In [50]:
titanic.head(10)

,name,gender,age,class,embarked,country,ticketno,fare,survived,pclass,crew
0,"Abbing, Mr. Anthony",male,42.0,3rd,S,United States,5547.0,7.1100,0,3.0,NaN
1,"Abbott, Mr. Eugene Joseph",male,13.0,3rd,S,United States,2673.0,20.0500,0,3.0,NaN
2,"Abbott, Mr. Rossmore Edward",male,16.0,3rd,S,United States,2673.0,20.0500,0,3.0,NaN
3,"Abbott, Mrs. Rhoda Mary 'Rosa'",female,39.0,3rd,S,England,2673.0,20.0500,1,3.0,NaN
4,"Abelseth, Miss. Karen Marie",female,16.0,3rd,S,Norway,348125.0,7.1300,1,3.0,NaN
5,"Abelseth, Mr. Olaus Jørgensen",male,25.0,3rd,S,United States,348122.0,7.1300,1,3.0,NaN
6,"Abelson, Mr. Samuel",male,30.0,2nd,C,France,3381.0,24.0000,0,2.0,NaN
7,"Abelson, Mrs. Hannah",female,28.0,2nd,C,France,3381.0,24.0000,1,2.0,NaN
8,"Abī-Al-Munà, Mr. Nāsīf Qāsim",male,27.0,3rd,C,Lebanon,2699.0,18.1509,1,3.0,NaN
9,"Abrahamsson, Mr. Abraham August Johannes",male,20.0,3rd,S,Finland,3101284.0,7.1806,1,3.0,NaN

7\. The variable `pclass` measures the class for passengers. Why are some of the values in this column `NaN`? Should this variable be categorical or quantitative? What type does Pandas this it is?

**Because not all passengers on board were customers, some were crew members. It should be categorical, but pandas has it as a quantitative variable**

In [51]:
titanic.dtypes

name         object
gender       object
age         float64
class        object
embarked     object
country      object
ticketno    float64
fare        float64
survived      int64
pclass      float64
crew         object
dtype: object

8\. Write code to cast `pclass` to the correct type. Repeat for any other variables that do not have the correct type.

In [52]:
titanic["pclass"] = titanic["pclass"].astype("category")
titanic["ticketno"] = titanic["ticketno"].astype("category")

## Transforming Categorical Variables

A categorical variable can be transformed by mapping its levels to new levels. For example, we may only be interested in whether a person on the titanic was a passenger or a crew member. The variable `class` is too detailed for these purposes. We can create a new variable, `type`, that is derived from the existing variable `class`. Observations with a `class` of "1st", "2nd", or "3rd" get a value of "passenger", while observations with a `class` of "deck crew", "engineering crew", or "deck crew" get a value of "crew".

In [53]:
titanic["type"] = titanic["class"].map({
    "1st": "passenger",
    "2nd": "passenger",
    "3rd": "passenger",
    "victualling crew": "crew",
    "engineering crew": "crew",
    "deck crew": "crew"
})

titanic

,name,gender,age,class,embarked,country,ticketno,fare,survived,pclass,crew,type
0,"Abbing, Mr. Anthony",male,42.0,3rd,S,United States,5547.0,7.11,0,3.0,NaN,passenger
1,"Abbott, Mr. Eugene Joseph",male,13.0,3rd,S,United States,2673.0,20.05,0,3.0,NaN,passenger
2,"Abbott, Mr. Rossmore Edward",male,16.0,3rd,S,United States,2673.0,20.05,0,3.0,NaN,passenger
3,"Abbott, Mrs. Rhoda Mary 'Rosa'",female,39.0,3rd,S,England,2673.0,20.05,1,3.0,NaN,passenger
4,"Abelseth, Miss. Karen Marie",female,16.0,3rd,S,Norway,348125.0,7.13,1,3.0,NaN,passenger
...,...,...,...,...,...,...,...,...,...,...,...,...
2202,"Wynn, Mr. Walter",male,41.0,deck crew,B,England,NaN,NaN,1,NaN,deck crew,crew
2203,"Yearsley, Mr. Harry",male,40.0,victualling crew,S,England,NaN,NaN,1,NaN,victualling crew,crew
2204,"Young, Mr. Francis James",male,32.0,engineering crew,S,England,NaN,NaN,0,NaN,engineering crew,crew
2205,"Zanetti, Sig. Minio",male,20.0,restaurant staff,S,England,NaN,NaN,0,NaN,restaurant staff,NaN
2206,"Zarracchi, Sig. L.",male,26.0,restaurant staff,S,England,NaN,NaN,0,NaN,restaurant staff,NaN

Upon closer inspection of this `DataFrame`, we see that we accidentally left out the level "restaurant staff" in the input to `.map()`. Any levels that are unspecified will be mapped to the missing value `NaN`.

This suggests a more concise way to define the new variable `type`. We can specify only the levels for passengers in the mapping and then fill in the missing values afterwards.

In [54]:
titanic["type"] = titanic["class"].map({
    "1st": "passenger",
    "2nd": "passenger",
    "3rd": "passenger"
})

# Replace all missing values by "crew"
titanic["type"].fillna("crew", inplace=True)

titanic

<positron-console-cell-54>:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

,name,gender,age,class,embarked,country,ticketno,fare,survived,pclass,crew,type
0,"Abbing, Mr. Anthony",male,42.0,3rd,S,United States,5547.0,7.11,0,3.0,NaN,passenger
1,"Abbott, Mr. Eugene Joseph",male,13.0,3rd,S,United States,2673.0,20.05,0,3.0,NaN,passenger
2,"Abbott, Mr. Rossmore Edward",male,16.0,3rd,S,United States,2673.0,20.05,0,3.0,NaN,passenger
3,"Abbott, Mrs. Rhoda Mary 'Rosa'",female,39.0,3rd,S,England,2673.0,20.05,1,3.0,NaN,passenger
4,"Abelseth, Miss. Karen Marie",female,16.0,3rd,S,Norway,348125.0,7.13,1,3.0,NaN,passenger
...,...,...,...,...,...,...,...,...,...,...,...,...
2202,"Wynn, Mr. Walter",male,41.0,deck crew,B,England,NaN,NaN,1,NaN,deck crew,crew
2203,"Yearsley, Mr. Harry",male,40.0,victualling crew,S,England,NaN,NaN,1,NaN,victualling crew,crew
2204,"Young, Mr. Francis James",male,32.0,engineering crew,S,England,NaN,NaN,0,NaN,engineering crew,crew
2205,"Zanetti, Sig. Minio",male,20.0,restaurant staff,S,England,NaN,NaN,0,NaN,restaurant staff,crew
2206,"Zarracchi, Sig. L.",male,26.0,restaurant staff,S,England,NaN,NaN,0,NaN,restaurant staff,crew

For more complex mappings, the `.map()` method also accepts a function. So the above is equivalent to

In [55]:
def class_to_type(c):
  if c in ["1st", "2nd", "3rd"]:
    return "passenger"
  else:
    return "crew"

titanic["class"].map(class_to_type)

0       passenger
1       passenger
2       passenger
3       passenger
4       passenger
          ...
2202         crew
2203         crew
2204         crew
2205         crew
2206         crew
Name: class, Length: 2207, dtype: object

## Converting Quantitative Variables to Categorical Variables

Sometimes it is necessary to categorize quantitative variables. We can use the `cut` function in `pandas` to categorize or bin a quantitative variable, by specifying the endpoints of the bins. We can also provide labels for the bins.

In [56]:
titanic["age_categories"] = pd.cut(x = titanic["age"],
                                      bins = [0, 18, 30, 45, 65, 130],
                                      labels = ["<18", "18-30", "30-45", "45-65", "65+"])

titanic.head(10)

,name,gender,age,class,embarked,country,ticketno,fare,survived,pclass,crew,type,age_categories
0,"Abbing, Mr. Anthony",male,42.0,3rd,S,United States,5547.0,7.1100,0,3.0,NaN,passenger,30-45
1,"Abbott, Mr. Eugene Joseph",male,13.0,3rd,S,United States,2673.0,20.0500,0,3.0,NaN,passenger,<18
2,"Abbott, Mr. Rossmore Edward",male,16.0,3rd,S,United States,2673.0,20.0500,0,3.0,NaN,passenger,<18
3,"Abbott, Mrs. Rhoda Mary 'Rosa'",female,39.0,3rd,S,England,2673.0,20.0500,1,3.0,NaN,passenger,30-45
4,"Abelseth, Miss. Karen Marie",female,16.0,3rd,S,Norway,348125.0,7.1300,1,3.0,NaN,passenger,<18
5,"Abelseth, Mr. Olaus Jørgensen",male,25.0,3rd,S,United States,348122.0,7.1300,1,3.0,NaN,passenger,18-30
6,"Abelson, Mr. Samuel",male,30.0,2nd,C,France,3381.0,24.0000,0,2.0,NaN,passenger,18-30
7,"Abelson, Mrs. Hannah",female,28.0,2nd,C,France,3381.0,24.0000,1,2.0,NaN,passenger,18-30
8,"Abī-Al-Munà, Mr. Nāsīf Qāsim",male,27.0,3rd,C,Lebanon,2699.0,18.1509,1,3.0,NaN,passenger,18-30
9,"Abrahamsson, Mr. Abraham August Johannes",male,20.0,3rd,S,Finland,3101284.0,7.1806,1,3.0,NaN,passenger,18-30

Now we can treat the new variable as we would any other categorical variable.

In [57]:
titanic["age_categories"]

0       30-45
1         <18
2         <18
3       30-45
4         <18
        ...
2202    30-45
2203    30-45
2204    30-45
2205    18-30
2206    18-30
Name: age_categories, Length: 2207, dtype: category
Categories (5, object): ['<18' < '18-30' < '30-45' < '45-65' < '65+']

Arguments to the `cut` method can be specified to determine the treatment of the bin endpoints, but we won't go into the details here. There is also a `qcut` method which creates bins based on quantiles (e.g., the endpoints are the 25th, 50th, and 75th percentiles (along with the min and max).)

## Back to the Exercises about the Titanic data...

10\. Create a new country column that contains only the values United States, United Kingdom, or Other. (At the time of the Titanic, the countries in the United Kingdom were England, Scotland, Wales, and Ireland, including what is now Northern Ireland.) Don't overwrite the original country column.

In [60]:
def country_remap(c):
    if c in ["England", "Scotland", "Wales", "Ireland"]:
        return "United Kingdom"
    elif c == "United States":
        return "United States"
    else:
        return "Other"

titanic["country_categories"] = titanic["country"].map(country_remap)
titanic.sample(5)

,name,gender,age,class,embarked,country,ticketno,fare,survived,pclass,crew,type,age_categories,country_categories
35,"Andersson, Miss. Ida Augusta Margareta",female,38.0,3rd,S,Sweden,347091.0,7.1506,0,3.0,NaN,passenger,30-45,Other
1840,"McGrady, Mr. James",male,17.0,victualling crew,S,England,NaN,NaN,0,NaN,victualling crew,crew,<18,United Kingdom
873,"Newell, Miss. Marjorie Anne",female,23.0,1st,C,United States,35273.0,113.0506,1,1.0,NaN,passenger,18-30,United States
1651,"Harris, Mr. Frederick",male,39.0,engineering crew,S,England,NaN,NaN,1,NaN,engineering crew,crew,30-45,United Kingdom
555,"Hocking, Mrs. Eliza",female,54.0,2nd,S,England,29105.0,23.0000,1,2.0,NaN,passenger,45-65,United Kingdom

11\. Create a new column that categorizes the fare variable into bins of length 5 from 0 to 25, bins of length 25 from 25 to 100, and 100+.

In [61]:
titanic["fare_categories"] = pd.cut(x = titanic["fare"],
                                      bins = [0, 5, 10, 15, 20, 25, 50, 75, 100, float("inf")],
                                      labels = ["<5", "5-10", "10-15", "15-20", "20-25", "25-50", "50-75", "75-100", "100+"])

titanic.head(10)

,name,gender,age,class,embarked,country,ticketno,fare,survived,pclass,crew,type,age_categories,country_categories,fare_categories
0,"Abbing, Mr. Anthony",male,42.0,3rd,S,United States,5547.0,7.1100,0,3.0,NaN,passenger,30-45,United States,5-10
1,"Abbott, Mr. Eugene Joseph",male,13.0,3rd,S,United States,2673.0,20.0500,0,3.0,NaN,passenger,<18,United States,20-25
2,"Abbott, Mr. Rossmore Edward",male,16.0,3rd,S,United States,2673.0,20.0500,0,3.0,NaN,passenger,<18,United States,20-25
3,"Abbott, Mrs. Rhoda Mary 'Rosa'",female,39.0,3rd,S,England,2673.0,20.0500,1,3.0,NaN,passenger,30-45,United Kingdom,20-25
4,"Abelseth, Miss. Karen Marie",female,16.0,3rd,S,Norway,348125.0,7.1300,1,3.0,NaN,passenger,<18,Other,5-10
5,"Abelseth, Mr. Olaus Jørgensen",male,25.0,3rd,S,United States,348122.0,7.1300,1,3.0,NaN,passenger,18-30,United States,5-10
6,"Abelson, Mr. Samuel",male,30.0,2nd,C,France,3381.0,24.0000,0,2.0,NaN,passenger,18-30,Other,20-25
7,"Abelson, Mrs. Hannah",female,28.0,2nd,C,France,3381.0,24.0000,1,2.0,NaN,passenger,18-30,Other,20-25
8,"Abī-Al-Munà, Mr. Nāsīf Qāsim",male,27.0,3rd,C,Lebanon,2699.0,18.1509,1,3.0,NaN,passenger,18-30,Other,15-20
9,"Abrahamsson, Mr. Abraham August Johannes",male,20.0,3rd,S,Finland,3101284.0,7.1806,1,3.0,NaN,passenger,18-30,Other,5-10

## Working with Gemini

Colab notebooks have [Gemini](), Google's AI, built in. Let's try it.

1\. Load either the Titanic data frame. After you load the data frame, there should be a button for "View recommended plot". Turn that button on and see what you get. Select one of the suggested plots that summarizes a single categorical variable. (Careful: make sure it's a single categorical variable. Some of the bar plots might be summarizing multiple variables.) What are features that you like about the plot? Are there any features you don't like?

2\. Now click on the "generate" with AI link, or the Gemini button. Write a prompt to reproduce some of your analysis from earlier in this notebook. You can copy and paste one of the questions, or you can try writing your own prompt. Run the code and examine the results. How successful was it?